name: Build and push Docker images

on: [release]

jobs: 
  dockerhub: 
    name: Build and push Docker images to DockerHub Registry
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - 
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          secrets: |
            GIT_AUTH_TOKEN=${{ github.token }}
          push: true
          tags: |
            montferret/chromium:latest
            montferret/chromium:${{ github.ref }}
  github:
      name: Build and push Docker images to GitHub Registry
      runs-on: ubuntu-latest
      steps:
        - 
          name: Checkout code
          uses: actions/checkout@v2
        - 
          name: Build and push
          uses: docker/build-push-action@v1
          with:
            registry: docker.pkg.github.com
            username: ${{ github.actor }}
            password: ${{ github.token }}
            repository: montferret/chromium
            tags: latest
            tag_with_ref: true
            add_git_labels: true
